{{- define "service-name" -}}
  {{- if .serviceName -}}
  {{ .serviceName }}
  {{- else -}}
  {{ .name }}-service-{{ .currentVersion | default .latestVersion }}
  {{- end -}}
{{- end -}}

{{- define "service-name-preview" -}} 
  {{- include "service-name" . }}-preview
{{- end -}} 

{{- define "path-name" -}}
{{- if eq $.Values.main .service.name -}}
{{ .service.name }}
{{- else -}}
({{ .service.name }}|)
{{- end -}}
{{- end -}}