{{- define "deployment.labels" }} 
  {{- $_ := set .service "type" "deployment" }}
  {{- $keel := .service.keel | default .Values.keel }}
  {{- include "labels" . }} 
    {{- if $keel.enabled }}
    keel.sh/policy: {{ $keel.policy | quote }}
    keel.sh/trigger: poll
    {{- end }}
  annotations:
    {{- if $keel.enabled }}
    keel.sh/pollSchedule: {{ $keel.pollSchedule | quote }}
    {{- end }}
{{- end }}