{{- define "labels" }} 
  {{- if index .service (print .service.type "Name") }}
  name: {{ index .service (print .service.type "Name") }}
  {{- else }}
  name: {{ .service.name }}-{{ .service.type }}-{{ .service.version }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .service.name }}
{{- include "labels.info" . | indent 2 }} 
{{- end }} 

{{- define "labels.info" }}
  tier: {{ .service.tier }}
  version: {{ .service.version }}
  release: {{ $.Values.release }}
{{- end }} 