# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: local-user
#   namespace: local
# ---
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: local-user
#   namespace: local
# rules:
#   - apiGroups: ["", "extensions", "apps"]
#     resources: ["*"]
#     verbs: ["*"]
# ---
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: local-user
#   namespace: local
# subjects:
# - kind: ServiceAccount
#   name: local-user
#   namespace: local
# roleRef:
#   kind: Role
#   name: local-user
#   apiGroup: rbac.authorization.k8s.io