{{- range $service := .Values.services }}
{{- range $version, $image := $service.version }}
{{- $_ := set $ "service" (merge dict $service)  }}
{{- $_ := set $.service "version" $version }}
{{- if $.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- include "service.labels" $ }}
spec:
  ports:
  {{- range $portName, $port := $service.port }}
  - name: {{ $portName }}
    targetPort: {{ $service.containerPort | default $portName }}
    port: {{ $port }}
    protocol: TCP
  {{- end }}
  selector:
    name: {{ $.service.name }}
    tier: {{ $.service.tier }}
    version: {{ $.service.version }}
    release: {{ $.Values.release }}
---
{{- end }}
{{- end }}
{{- end }}