{{- $_ := set $ "service" (merge dict .Values.services.app) }}
{{- range $version, $image := $.service.version }}
{{- $_ := set $.service "tag" $image.tag }}
{{- $_ := set $.service "version" $version }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  {{- include "secret.labels" $ }}
data:

{{- end }}
