{{- define "service-name" -}}
  {{- if .serviceName -}}
  {{ .serviceName }}
  {{- else -}}
  {{ .name }}-service-{{ .currentVersion | default .latestVersion }}
  {{- end -}}
{{- end -}}

{{- define "service-name-preview" }} 
  {{- include "service-name" . }}-preview
{{- end }} 

{{- define "path-name" -}}
  {{- $charList := splitList "" .name -}}
  
  {{- range $char := $charList -}}
  ({{- title $char -}}|{{- $char -}})
  {{- end -}}
{{- end -}}