{{- if .Values.services }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    name: api-ingress
    tier: backend
    release: {{ $.Values.release }}
  annotations:
    ingress.kubernetes.io/priority: "3"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^(/preview|)(/(v[0-9a-z.-]+)|/latest|)(.*) $4"
    ingress.kubernetes.io/custom-response-headers: >
      Access-Control-Allow-Origin: *
    # ingress.kubernetes.io/auth-type: "forward"
    # ingress.kubernetes.io/auth-response-headers: x-data-username
    # ingress.kubernetes.io/auth-url: http://auth.{{ .Release.Namespace }}/auth/verify
spec:
  rules:
  - http:
      paths:
      {{- range $service := .Values.services }}
      {{- $_ := set $ "service" (merge dict $service) }}
      {{- if and $service.enabled $service.ingress.enabled }}
      - path: /{service:(latest/|){{ template "path-name" $.service }}}
        backend:
          serviceName: {{ template "service-name" $.service }}
          servicePort: {{  $service.ingress.port }}
       {{- if index $service "version" $service.latestVersion "blueGreen" }}
      - path: /preview/{service:(latest/|){{ template "path-name" $.service }}}
        backend:
          serviceName: {{ template "service-name" $.service }}-preview
          servicePort: {{ $service.ingress.port }}
      {{- end }}
      {{- range $version, $image := $service.version }}
      {{- $_ := set $.service "currentVersion" $version }}
      - path: /{{ $version }}/{service:{{ template "path-name" $.service }}}
        backend:
          serviceName: {{ template "service-name" $.service }}
          servicePort: {{ $service.ingress.port }}
      {{- if $image.blueGreen }}
      - path: /preview/{{ $version }}/{service:{{ template "path-name" $.service }}}
        backend:
          serviceName: {{ template "service-name" $.service }}-preview
          servicePort: {{ $service.ingress.port }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
    {{- if .Values.host }}
    host: {{ .Values.host }}
    {{- end }}
{{- end }}
